### ISSUE TITLE
Composer не знает такого пакета

### ISSUE THREAD

**Issue by superromeo** [yoomoney/cms-drupal8#13]
При
`composer require drupal/commerce_yookassa`

получаю:
> $ composer update
> Gathering patches for root package.
> Loading composer repositories with package information
> Updating dependencies
> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - Root composer.json requires drupal/commerce_yookassa, it could not be found in any version, there may be a typo in the package name.
> 
> Potential causes:
>  - A typo in the package name
>  - The package is not available in a stable-enough version according to your minimum-stability setting
>    see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
>  - It's a private package and you forgot to add a custom repository to find it
> 
> Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Если добавить репозиторий, то всё работает, но это не удобно.

**Comment by ostulov** [comment]
Исправили
