### ISSUE TITLE
Error: Call to a member function id() on null в PaymentGateway\OffsitePaymentGatewayBase->getNotifyUrl()

### ISSUE THREAD

**Issue by superromeo** [yoomoney/cms-drupal8#16]
Когда я добавляю новый платёжный шлюз, и если в блоке "Условия" нажимать любые чекбоксы, то вылезает ошибка:

Тип | php
четверг, 7 октября 2021 - 17:33
Администратор
Место: http://ru.lom.localhost/admin/commerce/config/payment-gateways/add?_wrapper_format=drupal_ajax&ajax_form=1
Источник отсылки: http://ru.lom.localhost/admin/commerce/config/payment-gateways/add

> Error: Call to a member function id() on null в Drupal\commerce_payment\Plugin\Commerce\PaymentGateway\OffsitePaymentGatewayBase->getNotifyUrl() (строка 19 из /var/www/lom/web/modules/contrib/commerce/modules/payment/src/Plugin/Commerce/PaymentGateway/OffsitePaymentGatewayBase.php)
#0 /var/www/lom/web/modules/contrib/commerce_yookassa/src/Plugin/Commerce/PaymentGateway/YooKassa.php(248): Drupal\commerce_payment\Plugin\Commerce\PaymentGateway\OffsitePaymentGatewayBase->getNotifyUrl()
#1 /var/www/lom/web/modules/contrib/commerce/src/Plugin/Commerce/InlineForm/PluginConfiguration.php(104): Drupal\yookassa\Plugin\Commerce\PaymentGateway\YooKassa->buildConfigurationForm()
#2 /var/www/lom/web/modules/contrib/commerce/modules/payment/src/Form/PaymentGatewayForm.php(129): Drupal\commerce\Plugin\Commerce\InlineForm\PluginConfiguration->buildInlineForm()
#3 /var/www/lom/web/core/lib/Drupal/Core/Entity/EntityForm.php(106): Drupal\commerce_payment\Form\PaymentGatewayForm->form()
#4 /var/www/lom/web/modules/contrib/commerce/modules/payment/src/Form/PaymentGatewayForm.php(65): Drupal\Core\Entity\EntityForm->buildForm()
#5 [internal function]: Drupal\commerce_payment\Form\PaymentGatewayForm->buildForm()
#6 /var/www/lom/web/core/lib/Drupal/Core/Form/FormBuilder.php(532): call_user_func_array()
#7 /var/www/lom/web/core/lib/Drupal/Core/Form/FormBuilder.php(371): Drupal\Core\Form\FormBuilder->retrieveForm()
#8 /var/www/lom/web/core/lib/Drupal/Core/Form/FormBuilder.php(629): Drupal\Core\Form\FormBuilder->rebuildForm()
#9 /var/www/lom/web/core/lib/Drupal/Core/Form/FormBuilder.php(321): Drupal\Core\Form\FormBuilder->processForm()
#10 /var/www/lom/web/core/lib/Drupal/Core/Controller/FormController.php(73): Drupal\Core\Form\FormBuilder->buildForm()
#11 /var/www/lom/web/core/modules/layout_builder/src/Controller/LayoutBuilderHtmlEntityFormController.php(39): Drupal\Core\Controller\FormController->getContentResult()
#12 [internal function]: Drupal\layout_builder\Controller\LayoutBuilderHtmlEntityFormController->getContentResult()
#13 /var/www/lom/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(123): call_user_func_array()
#14 /var/www/lom/web/core/lib/Drupal/Core/Render/Renderer.php(578): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
#15 /var/www/lom/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(124): Drupal\Core\Render\Renderer->executeInRenderContext()
#16 /var/www/lom/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(97): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext()
#17 /var/www/lom/vendor/symfony/http-kernel/HttpKernel.php(158): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
#18 /var/www/lom/vendor/symfony/http-kernel/HttpKernel.php(80): Symfony\Component\HttpKernel\HttpKernel->handleRaw()
#19 /var/www/lom/web/core/lib/Drupal/Core/StackMiddleware/Session.php(57): Symfony\Component\HttpKernel\HttpKernel->handle()
#20 /var/www/lom/web/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(47): Drupal\Core\StackMiddleware\Session->handle()
#21 /var/www/lom/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(106): Drupal\Core\StackMiddleware\KernelPreHandle->handle()
#22 /var/www/lom/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(85): Drupal\page_cache\StackMiddleware\PageCache->pass()
#23 /var/www/lom/web/core/modules/ban/src/BanMiddleware.php(50): Drupal\page_cache\StackMiddleware\PageCache->handle()
#24 /var/www/lom/web/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(47): Drupal\ban\BanMiddleware->handle()
#25 /var/www/lom/web/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(52): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle()
#26 /var/www/lom/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle()
#27 /var/www/lom/web/core/lib/Drupal/Core/DrupalKernel.php(717): Stack\StackedHttpKernel->handle()
#28 /var/www/lom/web/index.php(19): Drupal\Core\DrupalKernel->handle()
#29 {main}
.

**Comment by superromeo** [comment]
После обновления до версии 2.2.1 ошибка не ушла.

**Comment by ostulov** [comment]
Добрый день!

Благодарю за сообщение, подготовим исправление.

**Comment by ostulov** [comment]
Сделали исправление этой проблемы в последней версии модуля v2.2.2
