### ISSUE TITLE
TypeError: array_keys(): Argument #1 ($array) must be of type array, string given в array_keys()

### ISSUE THREAD

**Issue by superromeo** [yoomoney/cms-drupal8#17]
После установки флажка "Отправлять в ЮKassa данные для чеков (54-ФЗ)" при оплате появляется ошибка:
> Место | http://ru.lom.localhost/checkout/11853/payment
Источник отсылки | http://ru.lom.localhost/checkout/11853/order_information
TypeError: array_keys(): Argument #1 ($array) must be of type array, string given в array_keys() (строка 83 из /var/www/lom/web/modules/contrib/commerce_yookassa/src/PluginForm/YooKassa/PaymentOffsiteForm.php)#0 /var/www/lom/web/modules/contrib/commerce_yookassa/src/PluginForm/YooKassa/PaymentOffsiteForm.php(83): array_keys() #1 /var/www/lom/web/modules/contrib/commerce/modules/payment/src/Plugin/Commerce/InlineForm/PaymentGatewayForm.php(108): Drupal\yookassa\PluginForm\YooKassa\PaymentOffsiteForm->buildConfigurationForm() #2 /var/www/lom/web/modules/contrib/commerce/modules/payment/src/Plugin/Commerce/CheckoutPane/PaymentProcess.php(218): Drupal\commerce_payment\Plugin\Commerce\InlineForm\PaymentGatewayForm->buildInlineForm() #3 /var/www/lom/web/modules/contrib/commerce/modules/checkout/src/Plugin/Commerce/CheckoutFlow/CheckoutFlowWithPanesBase.php(546): Drupal\commerce_payment\Plugin\Commerce\CheckoutPane\PaymentProcess->buildPaneForm() #4 [internal function]: Drupal\commerce_checkout\Plugin\Commerce\CheckoutFlow\CheckoutFlowWithPanesBase->buildForm() #5 /var/www/lom/web/core/lib/Drupal/Core/Form/FormBuilder.php(532): call_user_func_array() #6 /var/www/lom/web/core/lib/Drupal/Core/Form/FormBuilder.php(278): Drupal\Core\Form\FormBuilder->retrieveForm() #7 /var/www/lom/web/core/lib/Drupal/Core/Form/FormBuilder.php(219): Drupal\Core\Form\FormBuilder->buildForm() #8 /var/www/lom/web/modules/contrib/commerce/modules/checkout/src/Controller/CheckoutController.php(143): Drupal\Core\Form\FormBuilder->getForm() #9 [internal function]: Drupal\commerce_checkout\Controller\CheckoutController->formPage() #10 /var/www/lom/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(123): call_user_func_array() #11 /var/www/lom/web/core/lib/Drupal/Core/Render/Renderer.php(578): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() #12 /var/www/lom/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(124): Drupal\Core\Render\Renderer->executeInRenderContext() #13 /var/www/lom/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(97): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext() #14 /var/www/lom/vendor/symfony/http-kernel/HttpKernel.php(158): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() #15 /var/www/lom/vendor/symfony/http-kernel/HttpKernel.php(80): Symfony\Component\HttpKernel\HttpKernel->handleRaw() #16 /var/www/lom/web/core/lib/Drupal/Core/StackMiddleware/Session.php(57): Symfony\Component\HttpKernel\HttpKernel->handle() #17 /var/www/lom/web/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(47): Drupal\Core\StackMiddleware\Session->handle() #18 /var/www/lom/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(106): Drupal\Core\StackMiddleware\KernelPreHandle->handle() #19 /var/www/lom/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(85): Drupal\page_cache\StackMiddleware\PageCache->pass() #20 /var/www/lom/web/core/modules/ban/src/BanMiddleware.php(50): Drupal\page_cache\StackMiddleware\PageCache->handle() #21 /var/www/lom/web/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(47): Drupal\ban\BanMiddleware->handle() #22 /var/www/lom/web/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(52): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle() #23 /var/www/lom/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle() #24 /var/www/lom/web/core/lib/Drupal/Core/DrupalKernel.php(717): Stack\StackedHttpKernel->handle() #25 /var/www/lom/web/index.php(19): Drupal\Core\DrupalKernel->handle() #26 {main}.

**Comment by superromeo** [comment]
Проверил.
Очистил кэш, поставил галку, Оплата - та же ошибка.

В 
> if (in_array($taxUuid, array_keys($config['yookassa_tax']))) {

`$config['yookassa_tax'] == ''`

**Comment by ostulov** [comment]
Сделали исправление этой проблемы в последней версии модуля v2.2.2
