### ISSUE TITLE
Ошибка оплаты

### ISSUE THREAD

**Issue by antiden** [yoomoney/cms-drupal8#2]
Добрый!

Для неавторизованного пользователя после просмотра заказа и попытке перехода на сайт яндекса для оплаты выходит ошибка:
`YandexCheckout\Common\Exceptions\InvalidRequestException: Failed to build request "YandexCheckout\Request\Payments\CreatePaymentRequest": "Both email and phone values are empty in receipt" in YandexCheckout\Common\AbstractRequestBuilder->build() (line 75 of /site.ru/vendor/yandex-money/yandex-checkout-sdk-php/lib/Common/AbstractRequestBuilder.php).`

Для авторизованного покупателя все работает хорошо.

Drupal 8.6.4
Commerce 8.x-2.11
Yandex Checkout Module 1.0.0
SDK updated

**Comment by ostulov** [comment]
Добрый день!

Уточните, для неавторизованного пользователя при оформлении заказа запрашивается номер телефона или почта?
Использует ли магазин фискализацию через Яндекс.Кассу?

**Comment by antiden** [comment]
Добрый день!

1. При оформлении для неавторизованного пользователя запрашивается:
- Контактная информация: Email - ядро
- Платежная информация: Страна - по умолчанию Россия - ядро, Телефон - собственное поле

2.  Стоит чек для Отправлять в Яндекс.Кассу данные для чеков (54-ФЗ)

**Comment by ostulov** [comment]
Исправлено в предыдущем обновлении
