### ISSUE TITLE
YooKassa требует модуль Rules

### ISSUE THREAD

**Issue by superromeo** [yoomoney/cms-drupal8#24]
`YooKassa` требует модуль `Rules` в файле `yookassa.info.yml`:
> dependencies:
>   ...
>   - rules

Но многие не используют модуль `rules`. Он должен быть опциональным.

**Comment by ostulov** [comment]
Добрый день!

В ближайшем обновлении модуль Rules станет обязательным для отправки второго чека по 54ФЗ. По этой причине модуль  останется в списке зависимостей.

**Comment by superromeo** [comment]
Ясно. Но такая практика не очень хороша.
Имхо: Rules - тяжелый модуль, и его включение для какой-то мелочи может сильно подтормаживать сайт.
