### ISSUE TITLE
Название модуля отличается он названия пакета

### ISSUE THREAD

**Issue by superromeo** [yoomoney/cms-drupal8#25]
Пакет: `drupal/commerce_yookassa`
Модуль: `yookassa`

В Drupal подразумевается, что название пакета должно быть равно названию модуля.

В итоге получается так:
> wodby@php.container:/var/www/ololo $ drush en commerce_yookassa
> In PmCommands.php line 316:
>   Unable to install modules commerce_yookassa due to missing modules commerce
>   _yookassa.
> 

> wodby@php.container:/var/www/ololo $ drush en yookassa
>  [success] Successfully enabled: yookassa

Думаю, имеет смысл заменить название модуля на `commerce_yookassa`, чтобы не вводить админов в заблуждение :)

**Comment by ostulov** [comment]
Добрый день!

Благодарю за предложение, рассмотрим такую возможность!

**Comment by superromeo** [comment]
Спасибо!
