### ISSUE TITLE
Ну нужно дублировать в onReturn() действия из onNotify()

### ISSUE THREAD

**Issue by superromeo** [yoomoney/cms-drupal8#32]
Ну нужно дублировать в `public function onReturn(OrderInterface $order, Request $request)` действия из onNotify(). 
Так как повторно вызываются события, например, `OrderEvents::ORDER_PAID`.

**Comment by ostulov** [comment]
Добрый день!

Вызов события был добавлен по запросу https://github.com/yoomoney/cms-drupal8/issues/19
Можете, пожалуйста, более подробно описать, что сейчас не устраивает в работе модуля?

**Comment by superromeo** [comment]
Это событие вызывается дважды:
- после оплаты.
- после возвращения на сайт.

А должно только после оплаты.

**Comment by ostulov** [comment]
Для определения того, что оплата за заказ прошла успешно, используется два варианта:
- основной: уведомление об оплате, которое приходит в виде запроса
- дополнительный: если клиент нажмет на возврат в магазин

При обработке уведомления может возникнуть ошибка, а клиент не обязательно возвращается в магазин. Поэтому существуют два способа, и они друг друга дополняют.

**Comment by superromeo** [comment]
Это хорошо. 
Но Вы можете при возвращении в магазин проверять, были ли уже выполнены действия? 
И выполнять их только если они не были уже выполнены.

**Comment by ostulov** [comment]
Да, добавим такую проверку.

**Comment by superromeo** [comment]
Спасибо!

**Comment by ostulov** [comment]
Добавлено в последнем обновлении v2.2.8
